/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXC444
package_id: MCXC444VLH
mcu_data: ksdk2_0
processor_version: 25.06.10
board: FRDM-MCXC444
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 0fcc07ee-8768-4942-9f92-8d66fbde5778
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - commonSetting:
    - USART_RX_BUFFER_LEN: '64'
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LCD initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LCD'
- type: 'slcd'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'slcd_2.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LCD'
- config_sets:
  - fsl_slcd:
    - slcd_config:
      - powerSupply: 'kSLCD_InternalVll3UseChargePump'
      - voltageTrim: 'kSLCD_RegulatedVolatgeTrim00'
      - clkConfig_struct:
        - clockSource: 'kSLCD_AlternateClk1'
        - clockSourceFreq: 'ClocksTool_DefaultInit'
        - altClkDivider1: 'kSLCD_AltClkDivFactor512'
        - fastFrameRateEnable: 'false'
        - clkPrescaler: 'kSLCD_ClkPrescaler07'
      - dutyCycle: 'kSLCD_1Div4DutyCycle'
      - displayMode: 'kSLCD_NormalMode'
      - loadAdjust: 'kSLCD_LowLoadOrFastestClkSrc'
      - lowPowerBehavior: 'kSLCD_EnabledInWaitStop'
      - all_pins:
        - 0:
          - pinsFirstRow:
            - 0:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 1:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 2:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 3:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 4:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 5:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 6:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 7:
              - bool_array_item_t: 'true'
              - pinsOptions: 'fp'
            - 8:
              - bool_array_item_t: 'true'
              - pinsOptions: 'fp'
            - 9:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 10:
              - bool_array_item_t: 'true'
              - pinsOptions: 'fp'
            - 11:
              - bool_array_item_t: 'true'
              - pinsOptions: 'fp'
            - 12:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 13:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 14:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 15:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
          - pinsSecondRow:
            - 0:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 1:
              - bool_array_item_t: 'true'
              - pinsOptions: 'fp'
            - 2:
              - bool_array_item_t: 'true'
              - pinsOptions: 'bp'
            - 3:
              - bool_array_item_t: 'true'
              - pinsOptions: 'bp'
            - 4:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 5:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 6:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 7:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 8:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 9:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 10:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 11:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 12:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 13:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 14:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 15:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
        - 1:
          - pinsFirstRow:
            - 0:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 1:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 2:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 3:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 4:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 5:
              - bool_array_item_t: 'true'
              - pinsOptions: 'fp'
            - 6:
              - bool_array_item_t: 'true'
              - pinsOptions: 'fp'
            - 7:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 8:
              - bool_array_item_t: 'true'
              - pinsOptions: 'bp'
            - 9:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 10:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 11:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 12:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 13:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 14:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 15:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
          - pinsSecondRow:
            - 0:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 1:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 2:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 3:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 4:
              - bool_array_item_t: 'true'
              - pinsOptions: 'bp'
            - 5:
              - bool_array_item_t: 'true'
              - pinsOptions: 'fp'
            - 6:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 7:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 8:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 9:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 10:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 11:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 12:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 13:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 14:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
            - 15:
              - bool_array_item_t: 'false'
              - pinsOptions: 'fp'
      - enableFaultConfig: 'false'
      - faultConfig_struct:
        - faultDetectBackPlaneEnable: 'false'
        - faultDetectPinIndex: '0'
        - clock_config:
          - clockSource: 'BusInterfaceClock'
          - clockSourceFreq: 'ClocksTool_DefaultInit'
        - faultPrescaler: 'kSLCD_FaultSampleFreqDivider1'
        - width: 'kSLCD_FaultDetectWindowWidth4SampleClk'
        - interruptSources: ''
        - faultDetectIntEnable: 'false'
        - interrupt:
          - IRQn: 'LCD_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
slcd_config_t LCD_config = {
  .powerSupply = kSLCD_InternalVll3UseChargePump,
  .voltageTrim = kSLCD_RegulatedVolatgeTrim00,
  .clkConfig = &clkConfig,
  .dutyCycle = kSLCD_1Div4DutyCycle,
  .displayMode = kSLCD_NormalMode,
  .loadAdjust = kSLCD_LowLoadOrFastestClkSrc,
  .lowPowerBehavior = kSLCD_EnabledInWaitStop,
  .slcdLowPinEnabled = 920960,
  .slcdHighPinEnabled = 3146080,
  .backPlaneLowPin = 786432,
  .backPlaneHighPin = 1048832,
  .faultConfig = NULL
};
slcd_clock_config_t clkConfig = {
  .clkSource = kSLCD_AlternateClk1,
  .altClkDivider = kSLCD_AltClkDivFactor512,
  .fastFrameRateEnable = false,
  .clkPrescaler = kSLCD_ClkPrescaler07
};

static void LCD_init(void) {
  /* LCD initialization */
  SLCD_Init(LCD_PERIPHERAL, &LCD_config);
  /* Start LCD */
  SLCD_StartDisplay(LCD_PERIPHERAL);
}

/***********************************************************************************************************************
 * LPUART0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART0'
- type: 'lpuart_cmsis'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'lpuart_cmsis_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART0'
- config_sets:
  - general:
    - main_config:
      - operationMode: 'ARM_USART_MODE_ASYNCHRONOUS'
      - clockSource: 'LpuartClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - power_state: 'ARM_POWER_FULL'
      - baudRate_Bps: '115200'
      - dataBits: 'ARM_USART_DATA_BITS_8'
      - parityBit: 'ARM_USART_PARITY_NONE'
      - stopBit: 'ARM_USART_STOP_BITS_1'
      - enableRX: 'false'
      - enableRXBuffer: 'true'
      - enableTX: 'false'
      - signalEventFunctionId: 'NULL'
      - enableGetFreqFnCustomName: 'false'
      - getFreqFunctionCustomID: 'LPUART0_GetFreq'
      - enableInitPinsFnCustomName: 'false'
      - initPinFunctionCustomID: 'LPUART0_InitPins'
      - enableDeinitPinsFnCustomName: 'false'
      - deinitPinFunctionCustomID: 'LPUART0_DeinitPins'
  - fsl_cmsis_uart:
    - interrupt:
      - IRQn: 'LPUART0_IRQn'
      - enable_priority: 'false'
      - priority: '0'
    - quick_selection: 'default_edma'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Get clock source frequency */
uint32_t LPUART0_GetFreq(void){
  return LPUART0_CLOCK_SOURCE_FREQ;
};

static void LPUART0_init(void) {
  /* Initialize CMSIS USART */
  LPUART0_PERIPHERAL.Initialize(NULL);
  /* Power control of CMSIS USART */
  LPUART0_PERIPHERAL.PowerControl(ARM_POWER_FULL);
  /* Control of CMSIS USART */
  LPUART0_PERIPHERAL.Control(ARM_USART_MODE_ASYNCHRONOUS | ARM_USART_DATA_BITS_8 | ARM_USART_PARITY_NONE | ARM_USART_STOP_BITS_1, 115200);
  /* Enable or disable receiver. */
  LPUART0_PERIPHERAL.Control(ARM_USART_CONTROL_RX , 0);
  /* Enable or disable transmitter. */
  LPUART0_PERIPHERAL.Control(ARM_USART_CONTROL_TX , 0);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  LCD_init();
  LPUART0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
